var pastatypes = [
    "abissini",
    "acini di pepe",
    "affogaparini",
    "agnelotti",
    "agnoli",
    "agnolotti",
    "agnulot",
    "agoni bucati",
    "alfabeto",
    "amori",
    "aneletti",
    "anelletti",
    "anelli",
    "anellini",
    "anelloni",
    "anelloni d'africa",
    "angelotti",
    "aniduzzi",
    "armellette",
    "armelline",
    "arselle",
    "astri",
    "avena",
    "avena grande",
    "avermarie",
    "barbina",
    "barbine a nido",
    "bardele",
    "bassetti",
    "bavette",
    "bavette fini",
    "bavettine",
    "begnamusi",
    "biciclette",
    "bigoli",
    "blecs",
    "boccoli",
    "boccoloti",
    "boccolotti",
    "bombardoni",
    "bombaroni",
    "bucatini",
    "busa",
    "busiata",
    "busiate",
    "busiati",
    "caccavelle",
    "cagghiubbi",
    "caidos",
    "calamarata",
    "calamari",
    "campanelle",
    "candele",
    "canedeli",
    "canestri",
    "canestrini",
    "cannaciotti",
    "cannarone",
    "cannaroni rigati",
    "cannarune",
    "cannelloni",
    "cannelloni zitoni",
    "canneroncini",
    "cannerone",
    "canneroni",
    "canneroni grandi",
    "cannerozzi rigati",
    "cannoli",
    "cantaroggini",
    "capellasci",
    "capelli d'angelo",
    "capellini",
    "capellini fini",
    "capelvenere",
    "cappellacci",
    "cappelletti",
    "cappelli",
    "cappelli del prete",
    "cappellini",
    "cappettine",
    "capunti",
    "caramelle",
    "casarecce",
    "casarecci",
    "casoncelli",
    "casonsei",
    "casonsèi",
    "castellane",
    "casunziei",
    "cavasuneddi",
    "cavatappi",
    "cavatelli",
    "cavatieddi",
    "cavatielle",
    "cavatuneddi",
    "cazzarille",
    "cecamariti",
    "cecatelli",
    "cecatidde",
    "cellentani",
    "cencioni",
    "cerchionetti",
    "cesariccia",
    "chancierelle",
    "chicchi di riso",
    "chifferi",
    "chifferini",
    "cicatelli",
    "cicerchiole",
    "ciciarchiola",
    "cicioneddos",
    "cicorie",
    "cicorietta",
    "cinesini",
    "cinesi rigati",
    "cingule",
    "ciocchiolette",
    "cirillini",
    "ciriole",
    "ciufele",
    "ciuffolitti",
    "coccioline",
    "conchiglie",
    "conchigliette",
    "conchiglioni",
    "coralli",
    "corallini",
    "cornetti",
    "corni di bue",
    "cortecce",
    "corzetti",
    "creste di galli",
    "crestine",
    "crosetti",
    "croxetti",
    "crusetti",
    "culurgiones",
    "curzetti",
    "denti di cavallo",
    "denti di vecchia",
    "diavoletti",
    "diavolini",
    "ditaletti",
    "ditali",
    "ditalini",
    "doppio festone",
    "elefante",
    "eliche",
    "elicoidali",
    "fagioletti",
    "fagioloni",
    "fagottini",
    "farfalle",
    "farfalline",
    "farfallini",
    "farfalloni",
    "fazzoletti",
    "fazzoletti di seta",
    "fedelini",
    "fenescecchie",
    "fettucce",
    "fettuccelle",
    "fettucce romane",
    "fettuccine",
    "fiadi",
    "fide",
    "fide bucate",
    "fidelini",
    "fidelini bucati",
    "fidi",
    "filateddhi",
    "filatelli",
    "filati cu lu pirtuso",
    "fileja",
    "filini",
    "fiocconi",
    "fiochetti",
    "fiorentine",
    "fiori",
    "fiori di sambuco",
    "fischioni",
    "foglie di salice",
    "foglie d'ulivo",
    "folletti",
    "foratini",
    "fregola",
    "fregua",
    "fregula",
    "frese",
    "fresine",
    "freula",
    "frigulelli",
    "fugascion",
    "funghini",
    "fusarioi",
    "fusilli",
    "fusilli avellinesi",
    "fusilli bucati",
    "fusilli col buco",
    "fusilli rigati",
    "galani",
    "galla genovese",
    "ganghi di vecchia",
    "garganelli",
    "gasse",
    "gemelli",
    "gigantoni",
    "gigli",
    "girandole",
    "gnocchetti",
    "gnocchetti di ziti",
    "gnocchetti sardi",
    "gnocchettoni zitoni",
    "gnocchi",
    "gnocchi del ferro",
    "gnocchi di pane",
    "gnocchi di prete",
    "gnocculi",
    "gnucchitti",
    "gomiti",
    "gomitini",
    "gozziti",
    "gramigne",
    "gramignoni",
    "grattini",
    "grattoni",
    "incatenate",
    "knödel",
    "lagana",
    "lagane",
    "langaroli",
    "langheroli",
    "lanterne",
    "lasagna",
    "lasagne",
    "lasagnette",
    "lasagnoni",
    "lasagnotte",
    "lentine",
    "lesagnetes",
    "linguettine",
    "linguine",
    "lisanzedas",
    "long macaroni",
    "lorighittas",
    "lucciole",
    "lumache",
    "lumachelle",
    "lumachette",
    "lumachoni",
    "lunghetti",
    "macarones cravaos",
    "macaroni",
    "maccaronis de orgiu",
    "maccaruna di casa",
    "maccaruni aru ferru",
    "maccheroncelli",
    "maccheroncini",
    "maccheroncini di campofilone",
    "maccheroni",
    "maccheroni alla chitarra",
    "maccheroni alla molinara",
    "maccheroni al petine",
    "maccheroni bobbesi",
    "maccheronicini",
    "mafalde",
    "mafaldine",
    "magghietti",
    "malloreddus",
    "malmaritati",
    "maltagliati",
    "manatelli",
    "mandala",
    "mandilli di sea",
    "manfrigoli",
    "manfriguli",
    "maniche",
    "maniche di frate",
    "maniche rigate",
    "manicotti",
    "margaritine",
    "margherite lisce",
    "margherite rigate",
    "marille",
    "martaliai",
    "marziani",
    "matriciani",
    "mezzanelli",
    "mezzani",
    "mezzelune",
    "mezze maniche",
    "mezze penne",
    "mezze pennette lisce",
    "mezze zite",
    "mezzi bombardoni",
    "mezzi cocci",
    "midolline",
    "mignuicchi",
    "moccolotti",
    "mostaccioli",
    "napoletani",
    "nastri",
    "nastrini",
    "natalini",
    "nicci",
    "nocchette",
    "nodini",
    "occhi di bove",
    "occhi di elefante",
    "occhi di giudeo",
    "occhi di lupo",
    "occhi di pernice",
    "orecchie di prete",
    "orecchiette",
    "orzo",
    "paccheri",
    "pansoti",
    "pansotti",
    "paparele",
    "pappardelle",
    "papparelle",
    "paspardelle",
    "passatelli",
    "pasta al ceppo",
    "pastina",
    "pearl pasta",
    "penne",
    "penne a candela",
    "penne di natale",
    "penne di ziti",
    "penne regina",
    "penne ricce",
    "pennettine",
    "pennine",
    "pennuzze",
    "pentole",
    "perciatelli",
    "perciatellini",
    "perciatelloni",
    "piat d'angelot",
    "piccicasanti",
    "pici",
    "pillus",
    "pinci",
    "pincinelle",
    "piombi",
    "pipe",
    "pipe rigate",
    "pipette",
    "pirciati",
    "pizzelle",
    "pizzicarieddi",
    "pizzoccheri",
    "pizzocher di tei",
    "pizzocherini",
    "pochiacche",
    "presuner",
    "prigioneri",
    "puntalette",
    "punte d'ago",
    "puntine",
    "quadratini",
    "quadrefiore",
    "quadrellini",
    "quadretti",
    "quadrettini",
    "quadrotti",
    "quadrucci",
    "quaternei",
    "radiatori",
    "radichini",
    "ramicce",
    "ramicia",
    "rascatelli",
    "ravioli",
    "ravioli di magro",
    "recchie di prevete",
    "recchietele",
    "recchini",
    "rechelline",
    "regine",
    "reginelle",
    "reginette",
    "ricciarelle",
    "ricci di donna",
    "riccioli",
    "ricciolini",
    "ricciutelle",
    "rigatoncini",
    "rigatoni",
    "rigatoni romani",
    "risetto",
    "riso",
    "risone",
    "risoni",
    "ristoranti",
    "rombi",
    "rotelle",
    "rotelline",
    "rotine",
    "rotini",
    "ruote",
    "ruotelline",
    "ruotine",
    "sacchetti",
    "sacchettini",
    "sacchettoni",
    "sagnarelli",
    "sagne",
    "sagne 'ncannulate",
    "sagnette",
    "scaloppi",
    "schiaffoni",
    "sciablo",
    "sciabo",
    "scialatelli",
    "scialatielli",
    "sedani",
    "sedanini",
    "semi d'avena",
    "semi di cicoria",
    "semi di mela",
    "semi di melone",
    "semi di riso",
    "semi d'orzo",
    "semini",
    "semoni",
    "sfresatine",
    "sguazzabarbuz",
    "sigarette",
    "signorine",
    "sopracappellini",
    "sorprese",
    "spaccatelle",
    "spaghetti",
    "spaghetti alla chitarra",
    "spaghettini",
    "spaghettoni",
    "spilloni bucati",
    "spirali",
    "spiralini",
    "spole",
    "spruzzamusi",
    "squadrucchetti",
    "stacchiodde",
    "stelle",
    "stellette",
    "stellettine",
    "stortini",
    "straciamus",
    "strangolarpreti",
    "strangulaprievete",
    "strangulaprieviti",
    "strascenate",
    "strascinate",
    "strascinati",
    "strengozze",
    "stricchetti",
    "strichetti",
    "stringozzi",
    "strozzafrati",
    "strozzapreti",
    "subioti",
    "su filindeu",
    "taddarini",
    "tagghiarini",
    "tagghjunghele",
    "tagliarelli",
    "tagliatelle",
    "tagliatelle nervate",
    "tagliatelle smalzade",
    "tagliati di zitoni",
    "tagliatini",
    "taglierini",
    "tagliolini",
    "tagliolini a nido",
    "tajarin",
    "taraduzzi",
    "testaroli",
    "tofarelle",
    "tofettine",
    "tonnarelli",
    "torchio",
    "tordelli",
    "torsellini",
    "tortelli",
    "tortellini",
    "tortelloni",
    "tortiglioni",
    "trenette",
    "trenne",
    "trinette",
    "tripoline",
    "tripolini",
    "trivelli",
    "trofie",
    "trofiette",
    "truoccoli",
    "tubetti",
    "tubettini",
    "tubettini lunghi",
    "tuffoli",
    "tuffolini rigati",
    "tufoli",
    "tufoli rigati",
    "turtello",
    "umbrici",
    "vermicelli",
    "vermicelloni",
    "vermicelloni giganti",
    "vesuvio",
    "vrimiciddi",
    "zanne d'elefante",
    "zinnezinne",
    "zitellini",
    "ziti",
    "ziti candelati",
    "zitoni",
    "zituane"
]

var utils = {
  sample: function(array) {
    return array[
      Math.floor(Math.random() * array.length)
    ];
  },
  extend: function(a, b) {
    if (typeof b === "object") {
      for (var key in b) {
        if (b.hasOwnProperty(key)) {
          a[key] = b[key];
        }
      }
    }
    return a;
  },
};

var DB = function(){
  this.store = {};
};

DB.prototype.add = function(key, value) {
  if (this.store.hasOwnProperty(key)) {
    this.store[key].push(value);
  } else {
    this.store[key] = [value];
  }
};

DB.prototype.sample = function(key) {
  return utils.sample(this.store[key]);
};

var Chain = function(options){
  this.db = new DB();
  this.list = [];
  this.starter = "^";
  this.ender = "$";

  // default options
  this.options = utils.extend({
    novel: true,
    maxTries: 10,
    order: 3,
  }, options);
};

Chain.prototype.push = function(words) {
  var order = this.options.order;
  if (typeof words === "string") {
    words = [words];
  }
  for (var i = words.length - 1; i >= 0; i--) {
    var word = words[i];
    if (word.length < order) {
      continue;
    }

    this.list.push(word);
    word = word + "$";

    // add inital
    this.db.add(this.starter, word.substr(0, order));

    // add subsequent
    var length = word.length;
    for (var j = 0; j <= length - order - 1; j++) {
      var key = word.substr(j, order);
      var value = word[j + order];
      this.db.add(key, value);
    }
  }
};

Chain.prototype.check = function(word, options) {
  if (options.novel) {
    if (this.list.indexOf(word) >= 0) {
      return false;
    }
  }
  return true;
};

Chain.prototype.generate = function(options, depth) {
  // use global options.order; generate options.order is irrelevant
  var order = this.options.order;
  options = utils.extend(this.options, options);
  depth = depth || 0;
  if (depth > this.options.maxTries) {
    return null;
  }

  var word = this.db.sample(this.starter);
  for (var i = 100; i >= 0; i--) {
    var tail = word.substr(word.length - order, order);
    var next = this.db.sample(tail);
    if (next === this.ender || !next) {
      if (word[word.length - 1] === this.ender) {
        word = word.slice(0, word.length - 1);
      }
      break;
    } else {
      word = word + next;
    }
  }

  if (this.check(word, options)) {
    return word;
  } else {
    return this.generate(null, depth + 1);
  }
};


var Gibrish = Chain;

var gibrish = new Gibrish(novel=false);

gibrish.push(pastatypes);

function pasta() {
  return gibrish.generate();
}
